export default {
  SET_UI_STATUS: 'SET_UI_STATUS',
  SET_USER_PREFERENCE: 'SET_USER_PREFERENCE',
  SET_GLOBAL_APP_DATA: 'SET_GLOBAL_APP_DATA',

  ADD_SESSION: 'ADD_SESSION',
  DEL_SESSION: 'DEL_SESSION',
  DEL_ALL_SESSION: 'DEL_ALL_SESSION',
  DEL_OTHER_SESSION: 'DEL_OTHER_SESSION',

  ADD_CACHED_SESSION: 'ADD_CACHED_SESSION',
  DEL_CACHED_SESSION: 'DEL_CACHED_SESSION',
  DEL_ALL_CACHED_SESSION: 'DEL_ALL_CACHED_SESSION',
  DEL_OTHER_CACHED_SESSION: 'DEL_OTHER_CACHED_SESSION'
};
